### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by mikehardy**
The dependency change is just tracking the work in the Anki-Android repository, as separate commits. That was just to get the tree in shape for work

The main work is in [the final commit](https://github.com/ankidroid/apisample/commit/206b8a82804c20dac9791d865e6a16cf8d66657b)

The comment explains it, but to explain here: to solve the problem of background execution not working (https://github.com/ankidroid/Anki-Android/issues/4617) you can verify you get a "reasonable" (not-null && size >=1) list of decks from the API provider before doing anything, with a useful error message in case the list doesn't seem correct

### CODE REVIEW

**Comment by timrae** [comment]
Checking the size of the deck list seems a bit arbitrary, what exactly comes out null and in what situation?

**Comment by mikehardy** [comment]
Arbitrary or not: Research made me think it wasn't arbitrary - specifically people actually wish there wasn't a default deck at times https://github.com/ankidroid/Anki-Android/issues/2452#issuecomment-125522337 - but it never goes away, it is just hidden. Since the default deck will *always* be there, size >= 1 seems like a valid invariant

What comes out null and when: The API itself indicates that null is a valid value for getDecks to return but only "if there are problems". And in fact the list is null if there is an API provider installed, we do have permission, but background startup was prevented somehow (some vendors do this and started this bug, greenify can do it, I assume the system could prevent it for other reasons as well like resource constraints?)

So the second half / size check of that conditional could be removed and we could rely just on non-null response, but I thought as long as we have another alleged invariant (size >= 1) I could check for it to make sure things are working.

**Comment by timrae** [comment]
So basically any API function can potentially fail at any time then? In that case I don't think there's much point in checking before performing an operation, as it just introduces a race condition. Better just to provide a good way to indicate error from each API function itself without generating any null pointer exceptions

**Comment by mikehardy** [comment]
That conclusion seems right, yes - maybe a better PR would be to re-code the sample app commit to have null-safe / zero-safe access everywhere instead of a preliminary check that opens us to races in case the API provider is killed between check and access

It looks like the API is pretty well documented that nulls can happen already

**Comment by timrae** [comment]
Yeah, I think that's the better solution

**Comment by timrae** [comment]
Reopening in case you wanna edit it to just do the dependencies

**Comment by mikehardy** [comment]
yeah, easy to back out that one commit. Here's just the dependencies, I'll make a new one for defensive programming in the sample

**Pull request merged**
